---
name: Main

on:
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -e ".[testing]"

      - name: Run pytest
        run: |
          python -m pytest -vvv
